# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: build-and-test
run-name: Build and test across multiple operating systems, architectures and Bazel versions.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # This avoids building anything that wouldn't merge.
  lint-bazel-files:
    name: Lint all Bazel files
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup buildifier
      uses: jbajic/setup-buildifier@v1
    - name: Run buildifier
      run: |
        buildifier -mode check -r .
    - name: Update status badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: buildifier.json
        label: lint
        message: ${{ job.status == 'success' && 'pass' || 'fail' }}
        color: ${{ job.status == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'

  # This avoids building anything with bad documentation.
  generate-documentation:
    name: Regenerate documentation
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
    - name: Build documentation
      env:
        USE_BAZEL_VERSION: 9.0.0
      run: bazel build //docs/...
    - name: Update status badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: documentation.json
        label: docs
        message: ${{ job.status == 'success' && 'pass' || 'fail' }}
        color: ${{ job.status == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'

  # Only try and build if linting passes.
  checkout-setup-build-test:
    needs:
    - lint-bazel-files
    - generate-documentation

    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write
      
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'ubuntu-24.04_bazel-8.5.1_x86_64',  os: 'ubuntu-24.04',     bazel-version: '8.5.1' }
          - { name: 'ubuntu-24.04_bazel-8.5.1_aarch64', os: 'ubuntu-24.04-arm', bazel-version: '8.5.1' }
          - { name: 'macos-26_bazel-8.5.1_x86_64',      os: 'macos-26-intel',   bazel-version: '8.5.1' }
          - { name: 'macos-26_bazel-8.5.1_aarch64',     os: 'macos-26',         bazel-version: '8.5.1' }
          - { name: 'ubuntu-24.04_bazel-9.0.0_x86_64',  os: 'ubuntu-24.04',     bazel-version: '9.0.0' }
          - { name: 'ubuntu-24.04_bazel-9.0.0_aarch64', os: 'ubuntu-24.04-arm', bazel-version: '9.0.0' }
          - { name: 'macos-26_bazel-9.0.0_x86_64',      os: 'macos-26-intel',   bazel-version: '9.0.0' }
          - { name: 'macos-26_bazel-9.0.0_aarch64',     os: 'macos-26',         bazel-version: '9.0.0' }
    steps:

    # Remove unnecessary files to maximize build space.
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
      if: runner.os == 'Linux'

    # Checkout this repository and all submodules.
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: "google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa"
      with:
        workload_identity_provider: projects/771457463613/locations/global/workloadIdentityPools/github-automation/providers/build-dev
        service_account: github-automation-bot@gha-intrinsic-opensource-rcr.iam.gserviceaccount.com
        create_credentials_file: true

    # Setup bazel as a tool for building.
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0

    # Build and test: rmw_fastrtps_cpp
    - name: Build and test (rmw_fastrtps_cpp)
      continue-on-error: false
      id: rmw_fastrtps_cpp
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: |
        bazel build --@rmw_implementation//:rmw=rmw_fastrtps_cpp --config=ci
        bazel test --@rmw_implementation//:rmw=rmw_fastrtps_cpp --config=ci --jobs=1
    - name: Update status badge (rmw_fastrtps_cpp)
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: ${{ matrix.name }}_rmw_fastrtps_cpp.json
        label: ${{ matrix.bazel-version }}
        message: ${{ steps.rmw_fastrtps_cpp.outcome == 'success' && 'pass' || 'fail' }}
        color: ${{ steps.rmw_fastrtps_cpp.outcome == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'
    - name: Test report (rmw_fastrtps_cpp)
      uses: dorny/test-reporter@v2
      with:
        name: Bazel tests
        path: bazel-testlogs/**/test.xml
        reporter: java-junit
        fail-on-error: 'false'
      if: always()
    - name: Test logs (rmw_fastrtps_cpp)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }} (rmw_fastrtps_cpp)
        path: "bazel-testlogs/**/test.log"
      if: always()

    # Build and test: rmw_fastrtps_dynamic_cpp
    - name: Build and test (rmw_fastrtps_dynamic_cpp)
      continue-on-error: true
      id: rmw_fastrtps_dynamic_cpp
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: |
        bazel build --@rmw_implementation//:rmw=rmw_fastrtps_dynamic_cpp --config=ci
        bazel test --@rmw_implementation//:rmw=rmw_fastrtps_dynamic_cpp --config=ci --jobs=1
    - name: Update status badge (rmw_fastrtps_dynamic_cpp)
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: ${{ matrix.name }}_rmw_fastrtps_dynamic_cpp.json
        label: ${{ matrix.bazel-version }}
        message: ${{ steps.rmw_fastrtps_dynamic_cpp.outcome == 'success' && 'pass' || 'fail' }}
        color: ${{ steps.rmw_fastrtps_dynamic_cpp.outcome == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'
    - name: Test report (rmw_fastrtps_dynamic_cpp)
      uses: dorny/test-reporter@v2
      with:
        name: Bazel tests
        path: bazel-testlogs/**/test.xml
        reporter: java-junit
        fail-on-error: 'false'
      if: always()
    - name: Test logs (rmw_fastrtps_dynamic_cpp)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }} (rmw_fastrtps_dynamic_cpp)
        path: "bazel-testlogs/**/test.log"
      if: always()

    # Build and test: rmw_cyclonedds_cpp
    - name: Build and test (rmw_cyclonedds_cpp)
      continue-on-error: true
      id: rmw_cyclonedds_cpp
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: |
        bazel build --@rmw_implementation//:rmw=rmw_cyclonedds_cpp --config=ci
        bazel test --@rmw_implementation//:rmw=rmw_cyclonedds_cpp --config=ci --jobs=1
    - name: Update status badge (rmw_cyclonedds_cpp)
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: ${{ matrix.name }}_rmw_cyclonedds_cpp.json
        label: ${{ matrix.bazel-version }}
        message: ${{ steps.rmw_cyclonedds_cpp.outcome == 'success' && 'pass' || 'fail' }}
        color: ${{ steps.rmw_cyclonedds_cpp.outcome == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'
    - name: Test report (rmw_cyclonedds_cpp)
      uses: dorny/test-reporter@v2
      with:
        name: Bazel tests
        path: bazel-testlogs/**/test.xml
        reporter: java-junit
        fail-on-error: 'false'
      if: always()
    - name: Test logs (rmw_cyclonedds_cpp)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }} (rmw_cyclonedds_cpp)
        path: "bazel-testlogs/**/test.log"
      if: always()

    # Build and test: rmw_zenoh_cpp
    - name: Build and test (rmw_zenoh_cpp)
      continue-on-error: true
      id: rmw_zenoh_cpp
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: |
        bazel build @rmw_zenoh_cpp//:rmw_zenohd
        bazel run @rmw_zenoh_cpp//:rmw_zenohd 2>zenohd-stderr.log 1>zenohd-stdout.log &
        ZENOHD_PID=$!
        bazel build --@rmw_implementation//:rmw=rmw_zenoh_cpp --config=ci
        bazel test --@rmw_implementation//:rmw=rmw_zenoh_cpp --config=ci --jobs=1
        kill $ZENOHD_PID
    - name: Update status badge (rmw_zenoh_cpp)
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: f796805a77e0f05cc837b18e60142773
        filename: ${{ matrix.name }}_rmw_zenoh_cpp.json
        label: ${{ matrix.bazel-version }}
        message: ${{ steps.rmw_zenoh_cpp.outcome == 'success' && 'pass' || 'fail' }}
        color: ${{ steps.rmw_zenoh_cpp.outcome == 'success' && 'green' || 'red' }}
      if: always() && github.ref_name == 'main'
    - name: Test report (rmw_zenoh_cpp)
      uses: dorny/test-reporter@v2
      with:
        name: Bazel tests
        path: bazel-testlogs/**/test.xml
        reporter: java-junit
        fail-on-error: 'false'
      if: always()
    - name: Test logs (rmw_zenoh_cpp)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }} (rmw_zenoh_cpp)
        path: |
          "bazel-testlogs/**/test.log"
          "zenohd-stdout.log"
          "zenohd-stderr.log"
      if: always()


